---

- name: Open TCP ports
  ansible.builtin.firewalld:
    port: "{{item}}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 22
    - 80
    - 179
    - 443
    - 1025
    - 5473

- name: Calico UDP port
  ansible.builtin.firewalld:
    port: "4978/udp"
    permanent: yes
    state: enabled