---

# Configure containerd
- name: Configure cgroup for containerd 
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: SystemdCgroup = false
    line: SystemdCgroup = true
    state: present
    backup: yes


- name: Start containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Enable firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: yes