---
- name: kubernetes control plane initialization and configuration
  hosts: kcontr
  become: yes
  tasks:
    - name: initialize control plane
      ansible.builtin.shell:
        cmd: |
          kubeadm init \
          --apiserver-advertise-address=192.168.20.30 \
          --control-plane-endpoint=192.168.20.30 \
          --pod-network-cidr=192.168.0.0/16 \
          --upload-certs
    - name: copy kubeconfig to user directory
      ansible.builtin.shell:
        cmd: |
          mkdir -p /home/lain/.kube
          cp -i /etc/kubernetes/admin.conf /home/lain/.kube/config
          chown 1000:1000 /home/lain/.kube/config

- name: Configure Calico networking
  hosts: kcontr
  vars:
    calico_version: "v3.31.4"
    smb_driver_version: "v1.20.1"
  tasks:
    - name: Download Calico
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml
        dest: /tmp/tigera-operator.yaml
    - name: Download Calico resource definitions
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml
    - name: Download SMB Driver installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/{{ smb_driver_version }}/deploy/install-driver.sh
        dest: /tmp/install-driver.sh

    - name: Install python kubernetes module
      ansible.builtin.pip:
        name: 
          - kubernetes
          - openshift
        executable: pip3

    - name: Apply operator manifest
      kubernetes.core.k8s:
        state: present
        src: /tmp/tigera-operator.yaml

    - name: Wait for operator to spin up
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: tigera-operator
        namespace: tigera-operator
        wait: yes
        wait_condition:
          type: Available 
          status: "True"

    - name: Apply custom-resources
      kubernetes.core.k8s:
        state: present
        src: /tmp/custom-resources.yaml

    - name: Install SMB Driver
      ansible.builtin.shell: bash /tmp/install-driver.sh
