# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."lcache-dns" = {
    image = "lancachenet/lancache-dns:latest";
    environment = {
      "CACHE_DISK_SIZE" = "2000g";
      "CACHE_INDEX_SIZE" = "500m";
      "CACHE_MAX_AGE" = "3650d";
      "CACHE_ROOT" = "/lc";
      "DNS_BIND_IP" = "192.168.20.102";
      "LANCACHE_IP" = "192.168.20.102";
      "MIN_FREE_DISK" = "30g";
      "TZ" = "US/Central";
      "UPSTREAM_DNS" = "8.8.8.8";
      "USE_GENERIC_CACHE" = "true";
    };
    ports = [
      "53:53/udp"
      "53:53/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dns"
      "--network=lcache_default"
    ];
  };
  systemd.services."docker-lcache-dns" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lcache_default.service"
    ];
    requires = [
      "docker-network-lcache_default.service"
    ];
    partOf = [
      "docker-compose-lcache-root.target"
    ];
    wantedBy = [
      "docker-compose-lcache-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lcache-monolithic" = {
    image = "lancachenet/monolithic:latest";
    environment = {
      "CACHE_DISK_SIZE" = "2000g";
      "CACHE_INDEX_SIZE" = "500m";
      "CACHE_MAX_AGE" = "3650d";
      "CACHE_ROOT" = "/lc";
      "DNS_BIND_IP" = "192.168.20.102";
      "LANCACHE_IP" = "192.168.20.102";
      "MIN_FREE_DISK" = "30g";
      "TZ" = "US/Central";
      "UPSTREAM_DNS" = "8.8.8.8";
      "USE_GENERIC_CACHE" = "true";
    };
    volumes = [
      "/cache:/data/cache:rw"
      "/logs:/data/logs:rw"
    ];
    ports = [
      "8081:80/tcp"
      "4443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=monolithic"
      "--network=lcache_default"
    ];
  };
  systemd.services."docker-lcache-monolithic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lcache_default.service"
    ];
    requires = [
      "docker-network-lcache_default.service"
    ];
    partOf = [
      "docker-compose-lcache-root.target"
    ];
    wantedBy = [
      "docker-compose-lcache-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-lcache_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f lcache_default";
    };
    script = ''
      docker network inspect lcache_default || docker network create lcache_default
    '';
    partOf = [ "docker-compose-lcache-root.target" ];
    wantedBy = [ "docker-compose-lcache-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-lcache-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
