# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."plex" = {
    image = "plexinc/pms-docker";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:universal-package-install";
      "INSTALL_PACKAGES" = "ffmpeg";
      "INSTALL_PIP_PACKAGES" = "plexapi|requests";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
      "VERSION" = "docker";
    };
    volumes = [
      "/mnt/anime:/anime:rw"
      "/mnt/nas/plex:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-plex" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-plex-root.target"
    ];
    wantedBy = [
      "docker-compose-plex-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-plex-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
