---

- name: Enable controller specific firewall ports
  ansible.builtin.firewalld:
    port: "{{item}}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 6443
    - 2379-2380
    - 10251
    - 10252