# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mc_au-mc" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "ALLOW_FLIGHT" = "true";
      "DIFFICULTY" = "2";
      "ENABLE_WHITELIST" = "true";
      "EULA" = "TRUE";
      "MEMORY" = "8192M";
      "MOTD" = "Someone get Adam a Twisted Tea";
      "RCON_CMDS_STARTUP" = "/scoreboard objectives add Deaths deathCount
  /scoreboard objectives setdisplay list Deaths";
      "TYPE" = "PAPER";
      "TZ" = "America/Chicago";
      "VERSION" = "LATEST";
    };
    volumes = [
      "/mnt/nas/mc_au2:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=mc_au_default"
    ];
  };
  systemd.services."docker-mc_au-mc" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-mc_au_default.service"
    ];
    requires = [
      "docker-network-mc_au_default.service"
    ];
    partOf = [
      "docker-compose-mc_au-root.target"
    ];
    wantedBy = [
      "docker-compose-mc_au-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mc_au_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mc_au_default";
    };
    script = ''
      docker network inspect mc_au_default || docker network create mc_au_default
    '';
    partOf = [ "docker-compose-mc_au-root.target" ];
    wantedBy = [ "docker-compose-mc_au-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mc_au-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
