# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mc_au-mc_au" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "EULA" = "TRUE";
    };
    volumes = [
      "/mnt/nas/mc_au:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc_au"
      "--network=mc_au_default"
    ];
  };
  systemd.services."docker-mc_au-mc_au" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-mc_au_default.service"
    ];
    requires = [
      "docker-network-mc_au_default.service"
    ];
    partOf = [
      "docker-compose-mc_au-root.target"
    ];
    wantedBy = [
      "docker-compose-mc_au-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mc_au_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mc_au_default";
    };
    script = ''
      docker network inspect mc_au_default || docker network create mc_au_default
    '';
    partOf = [ "docker-compose-mc_au-root.target" ];
    wantedBy = [ "docker-compose-mc_au-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mc_au-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
