# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."plex" = {
    image = "lscr.io/linuxserver/plex:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "US/Central";
      "VERSION" = "docker";
    };
    volumes = [
      "/mnt/anime:/anime:rw"
      "/mnt/nas/plex:/config:rw"
    ];
    ports = [
      "32400:32400/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-plex" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-anime-root.target"
    ];
    wantedBy = [
      "docker-compose-anime-root.target"
    ];
  };
  virtualisation.oci-containers.containers."shoko_server" = {
    image = "ghcr.io/shokoanime/server:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "US/Central";
    };
    volumes = [
      "/mnt/nas/anime:/mnt/anime:rw"
      "/mnt/nas/shoko:/home/shoko/.shoko:rw"
    ];
    ports = [
      "8111:8111/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
      "--shm-size=268435456"
    ];
  };
  systemd.services."docker-shoko_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-anime-root.target"
    ];
    wantedBy = [
      "docker-compose-anime-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-anime-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
